spring:
  application:
    name: StreetFoodGo

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA2/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: changeme
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop #dev ovly
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true